# Dasharo project configuration data
file_version: 1.0.0

dasharo:
        platform: novacustom_nv4x
        newsletter:
                url:  https://newsletter.3mdeb.com/subscription/T61MyO2sP

client:
        name: NovaCustom

framework:
        name: coreboot
        version: e3e965b1
        url_template: https://github.com/Dasharo/coreboot/tree/COMMIT_HASH

components:
        - name: edk2
          version: 2020.03.17
          path: payloads/external/tianocore/tianocore
          url_template: https://github.com/Dasharo/edk2/tree/COMMIT_HASH
        - name: Blobs
          version: v1.0
          path: 3rdparty/dasharo-blobs
          url_template: https://gitlab.com/novacustom/blobs/-/tree/COMMIT_HASH

documentation:
        name: Dasharo Documentation
        url: https://docs.dasharo.com/
        overview_url: https://docs.dasharo.com/variants/novacustom_nv4x/overview/
        building_url: https://docs.dasharo.com/variants/novacustom_nv4x/building/
        flashing_url: https://docs.dasharo.com/variants/novacustom_nv4x/flashing_internal/

platform:
        vendor: NovaCustom
        model: NV4x

tests:
        hardware_matrix: https://docs.dasharo.com/variants/novacustom_nv4x/testing_configuration/
        results: https://docs.google.com/spreadsheets/d/1LOXY9HCu-fMitkYwX08iLsQdSNenzyU0LnMdVbZB5Do/edit#gid=0
        specification: https://docs.dasharo.com/unified-test-documentation/overview/

asciinema:
        signature_verification: https://asciinema.org/a/433461
