# Dasharo project configuration data
file_version: 0.0.1

dasharo:
  platform: msi_ms7d25
  newsletter:
    url:  https://newsletter.3mdeb.com/subscription/aKgTJjYEA

client:
  name: Zir Blazer

framework:
  name: coreboot
  version: a552cfc9
  url_template: https://github.com/Dasharo/coreboot/tree/COMMIT_HASH

components:
      - name: edk2
        version: 4d2846ba
        path: payloads/external/tianocore/Dasharo
        url_template: https://github.com/Dasharo/edk2/tree/COMMIT_HASH

documentation:
  name: Dasharo documentation
  url: https://docs.dasharo.com/
  building_url: https://docs.dasharo.com/variants/msi_z690/building-manual/
  flashing_url: https://docs.dasharo.com/variants/msi_z690/installation-manual/#flashing

platform:
  vendor: MSI
  model: PRO Z690-A WIFI DDR4

tests:
  specification: https://docs.dasharo.com/variants/msi_z690/test-matrix/
  hardware_matrix: https://docs.dasharo.com/variants/msi_z690/hardware-matrix/
  results: https://docs.google.com/spreadsheets/d/16wokQYhtS7XA1DQC3Om7FY-IImG6SZisGK7NnzyRGVY/edit?usp=sharing

asciinema:
  signature_verification: https://asciinema.org/a/486982
